name: Update receipt-pdf-generator psp info file

on:
  push:
    branches:
      - main
    paths:
      - "py-scripts/psp/output/psp_config_file.json"

  workflow_dispatch:

jobs:
  update_pdf_engine_psp_info_file:
    name: Update PSP info file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # prepare receipt-pdf-generator for engine
      # create tmp folder template
      # copy all needed files
      - name: Prepare file to transfer
        shell: bash
        id: transfer_file
        run: |
          cd py-scripts/psp/output
          mkdir -p tmp
          cp psp_config_file.json tmp/psp_config_file.json
      # open a PR on generator repo
      - name: Create pull request
        uses: jacopocarlini/action-pull-request-another-repo@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.BOT_TOKEN_GITHUB }}
        with:
          source_folder: "py-scripts/psp/output/tmp"
          destination_repo: "pagopa/pagopa-receipt-pdf-generator"
          destination_folder: "src/main/resources"
          destination_base_branch: "main"
          destination_head_branch: "pagopa-psp-info-configuration"
          user_email: "github-bot@pagopa.it"
          user_name: "pagopa-github-bot"
          allow_force_push: "true"
      - name: Create pull request to helpdesk
        uses: jacopocarlini/action-pull-request-another-repo@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.BOT_TOKEN_GITHUB }}
        with:
          source_folder: "py-scripts/psp/output/tmp"
          destination_repo: "pagopa/pagopa-receipt-pdf-helpdesk"
          destination_folder: "src/main/resources"
          destination_base_branch: "main"
          destination_head_branch: "pagopa-psp-info-configuration"
          user_email: "github-bot@pagopa.it"
          user_name: "pagopa-github-bot"
          allow_force_push: "true"